const KEY='minha_meta_v15';
const OLD_KEYS=['minha_meta_v14','minha_meta_v13','minha_meta_v12','minha_meta_v11','minha_meta_v10','minha_meta_v9'];
const fmt=n=>new Intl.NumberFormat('es-AR',{maximumFractionDigits:0}).format(Number(n||0));
const money=n=>'$ '+fmt(n);
const localISO=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const uid=()=>Date.now()+Math.floor(Math.random()*1000);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initial={version:15,cycleId:uid(),cycleName:'Ciclo atual',periodStart:'2026-09-01',periodEnd:'2026-10-05',obligationsGoal:0,safetyMargin:100000,goal:100000,obligations:[],lastBackup:null,selectedDate:localISO(),incomes:[],expenses:[],study:[],quality:{},reminders:[],dailyActivities:{},bills:[],budgets:[],cycles:[],plannedActivityOverrides:{},dayStatus:{}};
let data=JSON.parse(localStorage.getItem(KEY)||'null');
if(!data){for(const k of OLD_KEYS){try{const x=localStorage.getItem(k);if(x){data=JSON.parse(x);break}}catch{}}}
if(!data)data=initial;
const dailyPlan={0:[['🙏','Missa / compromisso religioso','check',null],['🚗','Trabalho','money',5],['📚','Revisão leve','hours',1]],1:[['🏫','Faculdade – manhã','check',null],['📚','Estudo de Bioquímica','hours',3],['🍳','Preparar comida','check',null],['🏋️','Treino com barra','check',null],['🙏','Formação / compromisso','check',null]],2:[['🏫','Faculdade – manhã','check',null],['🚗','Trabalho','money',4.5],['📚','Estudo','hours',3],['🏋️','Treino com barra','check',null]],3:[['🎾','Tênis + deslocamento','check',null],['🚗','Trabalho','money',8.5],['📚','Estudo / revisão','hours',1]],4:[['🏫','Faculdade – manhã','check',null],['🚗','Trabalho','money',4.5],['📚','Estudo','hours',3],['🏋️','Treino com barra','check',null]],5:[['🚗','Trabalho','money',8.5],['🏋️','Treino com barra','check',null],['🍳','Preparar comida','check',null],['🙏','Compromisso','check',null]],6:[['⚽','Futebol','check',null],['🚗','Trabalho','money',9.5],['📚','Revisão opcional','hours',1]]};
normalize();
function normalize(){
 data.version=15;data.incomes??=[];data.dayStatus??={};data.expenses??=[];data.study??=[];data.quality??={};data.reminders??=[];data.dailyActivities??={};data.bills??=[];data.budgets??=[];data.cycles??=[];data.plannedActivityOverrides??={};data.weeklyWorkTargets??={0:70000,1:0,2:59204,3:106250,4:64830,5:125455,6:142500};data.weeklyActivities??={};
 if(!Object.keys(data.weeklyActivities).length)data.weeklyActivities=Object.fromEntries(Object.entries(dailyPlan).map(([dow,items])=>[dow,items.map((x,i)=>({id:'base-'+dow+'-'+i,icon:x[0],name:x[1],metric:x[2],target:x[3]}))]));
 const activityKey=a=>{const n=(a.name||'').trim().toLowerCase();if(n.includes('tênis')||n.includes('tenis'))return 'sport-tennis';return (a.icon||'')+'|'+n};
 Object.keys(data.weeklyActivities).forEach(d=>{const seen=new Set();data.weeklyActivities[d]=(data.weeklyActivities[d]||[]).filter(a=>{const k=activityKey(a);if(seen.has(k))return false;seen.add(k);return true});});
 Object.keys(data.dailyActivities).forEach(d=>{const seen=new Set();data.dailyActivities[d]=(data.dailyActivities[d]||[]).filter(a=>{const k=activityKey(a);if(seen.has(k))return false;seen.add(k);return true});});
 data.selectedDate??=localISO();data.periodStart??='2026-09-01';data.periodEnd??='2026-10-05';data.safetyMargin??=100000;
 const existingBills=Array.isArray(data.bills)?data.bills:[];const legacyObs=Array.isArray(data.obligations)?data.obligations:[];const billSourceIds=new Set(existingBills.map(b=>b.id));
 const migrated=legacyObs.filter(o=>!o.sourceBillId||!billSourceIds.has(o.sourceBillId)).map(o=>({id:uid(),name:o.name||'Conta migrada',amount:Number(o.amount||0),due:data.periodEnd,note:o.note||'Migrada da versão anterior',paidAmount:0,paid:false,history:[],paymentPlan:{type:'single',installments:[]}}));
 if(!existingBills.length&&migrated.length)data.bills=migrated;else if(migrated.length)data.bills.push(...migrated);
 data.obligations=[];
 data.bills=data.bills.map(b=>({id:b.id??uid(),name:b.name||'Conta',amount:Number(b.amount||0),due:b.due||data.periodEnd,note:b.note||'',paidAmount:Number(b.paidAmount||0),paid:Boolean(b.paid),history:b.history||[],paymentPlan:b.paymentPlan||{type:'single',installments:[]}}));
 data.bills.forEach(b=>{b.paymentPlan.type??='single';b.paymentPlan.installments??=[];});
 data.cycles=data.cycles.map(c=>({...c,bills:c.bills||[]}));
 data.obligationsGoal=obligationTotal();data.goal=data.obligationsGoal+Number(data.safetyMargin||0);
 if(!data.cycleId)data.cycleId=uid();if(!data.cycleName)data.cycleName='Ciclo atual';rebuildBillPayments();
}
function obligationTotal(){return sum(data.bills,b=>b.amount)}
function recalcGoal(){data.obligationsGoal=obligationTotal();data.goal=data.obligationsGoal+Number(data.safetyMargin||0)}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function sum(a,f){return a.reduce((s,x)=>s+Number(f(x)||0),0)}
function formatDate(d){return new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'))}
function daysBetween(a,b){return Math.ceil((new Date(b+'T23:59:59')-new Date(a+'T00:00:00'))/86400000)+1}
function cycleDaysRemaining(){return Math.max(0,daysBetween(localISO(),data.periodEnd))}
function incomeTotal(){return sum(data.incomes,x=>x.amount)}
function expenseTotal(){return sum(data.expenses,x=>x.amount)}
function plannedGoals(){let total=0;for(let d=new Date(data.periodStart+'T12:00');d<=new Date(data.periodEnd+'T12:00');d.setDate(d.getDate()+1))total+=plannedGoalFor(d.toISOString().slice(0,10));return total}
const plannedGoalsByDay={0:70000,1:0,2:59204,3:106250,4:64830,5:125455,6:142500};
const plannedGoalOverrides={'2026-10-02':125456};
const plannedHoursByDay={0:5,1:0,2:4.5,3:8.5,4:4.5,5:8.5,6:9.5};
function plannedGoalFor(date){const dow=new Date(date+'T12:00').getDay();return data.plannedActivityOverrides?.[date]?.workTarget??plannedGoalOverrides[date]??(data.weeklyWorkTargets?.[dow]??plannedGoalsByDay[dow]??0)}
function futureWorkDates(){const out=[];const start=new Date(localISO()+'T12:00'), end=new Date(data.periodEnd+'T12:00');for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const iso=d.toISOString().slice(0,10);if(plannedGoalFor(iso)>0&&!data.dayStatus?.[iso]?.closed)out.push(iso)}return out}
function remainingWorkDays(){return futureWorkDates().length}
function plannedFutureTotal(){return sum(futureWorkDates(),d=>plannedGoalFor(d))}
function closedPlanDeficit(){return sum(Object.keys(data.dayStatus||{}).filter(d=>data.dayStatus[d]?.closed),d=>Math.max(0,plannedGoalFor(d)-incomeForDay(d)))}
function closedPlanSurplus(){return sum(Object.keys(data.dayStatus||{}).filter(d=>data.dayStatus[d]?.closed),d=>Math.max(0,incomeForDay(d)-plannedGoalFor(d)))}
function planningGap(){return Math.max(0,Number(data.goal||0)-incomeTotal())-plannedFutureTotal()}
function planningExcess(){return plannedFutureTotal()-Math.max(0,Number(data.goal||0)-incomeTotal())}
function planningStatus(){const gap=planningGap();if(Math.abs(gap)<0.5)return 'balanced';return gap>0?'short':'over'}
function dayPlan(date){const dow=new Date(date+'T12:00').getDay();const overrides=data.plannedActivityOverrides?.[date]||{};const base=(data.weeklyActivities?.[dow]||[]).map((x,i)=>{const id=x.id||'base-'+dow+'-'+i;const o=overrides[id]||{};if(o.removed)return null;return {id,icon:x.icon||'📌',name:o.name||x.name,metric:o.metric||x.metric,target:o.target??((o.metric||x.metric)==='money'?plannedGoalFor(date):x.target),done:Boolean(o.done),actual:o.actual??0,editable:true,weekly:true}}).filter(Boolean);return [...base,...(data.dailyActivities[date]||[])].map(x=>({...x,editable:x.editable!==false}))}
function activityProgress(a,date){if(a.metric==='money'){const actual=incomeForDay(date);const target=Number(a.target||plannedGoalFor(date));return {actual,target,pct:target?Math.min(100,actual/target*100):0,label:money(actual)+' / '+money(target)}}if(a.metric==='hours'){const actual=studyForDay(date);return {actual,target:Number(a.target||0),pct:a.target?Math.min(100,actual/a.target*100):0,label:actual.toFixed(1).replace('.',',')+'h / '+Number(a.target||0).toFixed(1).replace('.',',')+'h'}}return {actual:a.done?1:0,target:1,pct:a.done?100:0,label:a.done?'Concluída':'Pendente'}}
function incomeForDay(d){return sum(data.incomes.filter(x=>x.date===d),x=>x.amount)}
function studyForDay(d){return sum(data.study.filter(x=>x.date===d),x=>x.hours)}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0);render()}
function selected(){return data.selectedDate}
function selectDate(d){if(d){data.selectedDate=d;save()}}
function changeDay(n){const d=new Date(selected()+'T12:00');d.setDate(d.getDate()+n);data.selectedDate=d.toISOString().slice(0,10);save()}
function render(){
 const sd=selected(),income=incomeTotal(),expense=expenseTotal(),net=income-expense,goal=Number(data.goal||0),pct=goal?Math.min(100,income/goal*100):0,remaining=Math.max(0,goal-income),days=remainingWorkDays(),needed=days?Math.ceil(remaining/days):remaining,closed=Boolean(data.dayStatus?.[sd]?.closed),dayTarget=plannedGoalFor(sd),dayGain=incomeForDay(sd),dayDiff=dayGain-dayTarget,futurePlan=plannedFutureTotal(),gap=planningGap(),excess=planningExcess(),closedDeficit=closedPlanDeficit(),closedSurplus=closedPlanSurplus();
 const label=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(sd+'T12:00'));
 ['todayText','selectedDateLabel','routineDateLabel'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=(id==='todayText'?'Data selecionada: ':'')+label});['datePicker','routinePicker'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=sd});
 const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('goalValue',money(goal));set('goalPct',pct.toFixed(1).replace('.',',')+'% concluído');set('remaining',remaining? 'Faltam '+money(remaining):'Meta atingida');set('goalBasis','Ciclo: '+formatDate(data.periodStart)+' → '+formatDate(data.periodEnd));const bar=document.getElementById('goalBar');if(bar)bar.style.width=pct+'%';
 set('dailyGoal',plannedGoalFor(sd)?money(plannedGoalFor(sd)):'—');set('todayIncome',money(incomeForDay(sd)));set('todayExpense',money(sum(data.expenses.filter(x=>x.date===sd),x=>x.amount)));set('incomeAccumulated',money(income));set('netValue',money(net));
 set('statusText',dayTarget?(closed?(dayDiff>=0?'🟢 Dia concluído: excedente de '+money(dayDiff)+'.':'🔴 Dia concluído: faltaram '+money(-dayDiff)+'.'):(dayGain>=dayTarget?'🟢 Você já atingiu a meta do dia. O dia ainda está aberto.':'🟡 Faltam '+money(dayTarget-dayGain)+' para a meta do dia.')):'🔵 Sem meta financeira de trabalho neste dia.');set('averageText','Para terminar o ciclo no objetivo: '+money(needed)+' por dia de trabalho ainda aberto.');
 let audit='Planejamento restante: <b>'+money(futurePlan)+'</b> • ';if(Math.abs(gap)<0.5)audit+='🟢 Alinhado com o que ainda falta ganhar.';else if(gap>0)audit+='🟠 Faltam <b>'+money(gap)+'</b> no planejamento restante. Você escolhe onde redistribuir.';else audit+='🟢 Há <b>'+money(excess)+'</b> acima do necessário no planejamento dos dias abertos. Isso é margem de planejamento, não uma dívida e não altera a meta do ciclo.';if(closedDeficit>0.5)audit+=' • 🔴 Déficit acumulado dos dias concluídos: <b>'+money(closedDeficit)+'</b>.';if(closedSurplus>0.5)audit+=' • 🟢 Excedente dos dias concluídos: <b>'+money(closedSurplus)+'</b>.';const pa=document.getElementById('planAudit');if(pa)pa.innerHTML=audit;const pc=document.getElementById('planningControls');if(pc){pc.innerHTML=`<div class="summaryLine"><b>Meta necessária agora:</b> ${money(needed)} por dia de trabalho ainda aberto • <b>${days}</b> dia(s) aberto(s).</div><div class="summaryLine"><b>Falta ganhar:</b> ${money(remaining)}${closedDeficit>0.5?` • <b>Déficit acumulado:</b> ${money(closedDeficit)}`:''}${closedSurplus>0.5?` • <b>Excedente acumulado:</b> ${money(closedSurplus)}`:''}</div><div class="quick"><button onclick="editWeeklyTargets()">✏️ Editar metas por dia</button><button onclick="editWeeklyActivities()">⚙️ Editar rotina semanal</button>${gap>0.5?`<button onclick="openRedistribute()">🔄 Redistribuir + ${money(gap)}</button>`:''}</div>`}
 const q=data.quality[sd]||{};set('qualitySummary','Em '+formatDate(sd)+': treino – '+(q.treino||'não registrado')+' | alimentação – '+(q.alimentacao||'não registrada'));
 const rows=dayPlan(sd);const html=rows.map(a=>{const p=activityProgress(a,sd);return `<div class="routineRow ${p.pct>=100?'done':''}"><div><strong>${esc(a.icon)} ${esc(a.name)}</strong><small>${a.metric==='money'?'Meta financeira: '+money(p.target):a.metric==='hours'?'Meta de tempo: '+p.target+'h': 'Meta de conclusão'} • ${esc(p.label)}</small><div class="miniProgress"><span style="width:${p.pct}%"></span></div></div><div class="rowActions"><button onclick="editActivity('${sd}','${esc(a.id)}')">Editar</button><button class="danger" onclick="deleteActivity('${sd}','${esc(a.id)}')">Excluir</button>${a.metric==='check'?`<input type="checkbox" ${a.done?'checked':''} onchange="toggleActivity('${sd}','${esc(a.id)}')">`:''}</div></div>`}).join('');
 document.getElementById('dailySchedule').innerHTML=html;document.getElementById('dailyChecklist').innerHTML=html;document.getElementById('routineList').innerHTML=html;
 const ds=document.getElementById('dayStatusControls');if(ds){const st=data.dayStatus?.[sd];ds.innerHTML=st?.closed?`<div class="summaryLine"><b>✅ Dia concluído.</b> Resultado: ${money(dayGain)} • Meta: ${money(dayTarget)} • ${dayDiff>=0?'Excedente':'Déficit'}: ${money(Math.abs(dayDiff))}</div><button onclick="reopenDay('${sd}')">✏️ Reabrir dia e corrigir</button>`:`<div class="summaryLine">O dia está <b>aberto</b>. O app só redistribui diferenças depois que você confirmar que terminou o dia.</div><button class="success" onclick="closeDay('${sd}')">✅ Concluir dia</button>`}
 renderList('incomeList',data.incomes,'income');renderList('expenseList',data.expenses,'expense');set('expenseSummary','Total gasto: '+money(expense)+' • Extras: '+money(extraExpenses())+' • Orçado: '+money(expense-extraExpenses()));
 set('studyTotal','Total de estudos registrado: '+sum(data.study,x=>x.hours).toFixed(1).replace('.',',')+' horas');set('selectedStudyTotal','Neste dia: '+studyForDay(sd).toFixed(1).replace('.',',')+' horas');
 const upcoming=data.reminders.filter(r=>!r.done).sort((a,b)=>a.date.localeCompare(b.date));document.getElementById('reminderList').innerHTML=upcoming.length?upcoming.map(reminderHTML).join(''):'<div class="panel muted">Nenhum lembrete pendente.</div>';document.getElementById('homeReminders').innerHTML=upcoming.slice(0,3).map(reminderHTML).join('')||'<span class="muted">Nenhum lembrete pendente.</span>';
 renderObligations();renderBills();renderBudgets();renderAnalytics();renderCycles();renderSettings();renderFinancialOverview();
}
function renderList(id,list,type){const el=document.getElementById(id);if(!el)return;el.innerHTML=[...list].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="entry"><div><strong>${type==='income'?'💰':'💸'} ${money(x.amount)}</strong><small>${formatDate(x.date)} ${x.hours?'• '+x.hours+'h':''}${x.category?' • '+esc(x.category):''}${x.plannedType==='extra'?' • 🔴 Extra':x.plannedType==='budget'?' • 🟢 Orçamento':''}${x.note?' • '+esc(x.note):''}</small></div><div class="rowActions"><button onclick="editEntry('${type}',${x.id})">Editar</button><button class="danger" onclick="deleteEntry('${type}',${x.id})">Excluir</button></div></div>`).join('')||'<div class="panel muted">Nenhum registro ainda.</div>'}
function openModal(h){document.getElementById('modalContent').innerHTML=h;document.getElementById('modal').classList.remove('hidden')}function closeModal(){document.getElementById('modal').classList.add('hidden')}
function openIncome(existing){const x=existing||{};openModal(`<h2>${existing?'Editar ganho':'Registrar ganho'}</h2><label>Valor<input id="mAmount" type="number" value="${x.amount||''}"></label><label>Horas trabalhadas<input id="mHours" type="number" step=".5" value="${x.hours||''}"></label><label>Data<input id="mDate" type="date" value="${x.date||selected()}"></label><label>Observação<input id="mNote" value="${esc(x.note||'')}"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveIncome(${existing?x.id:''})">Salvar</button></div>`)}
function saveIncome(id){if(!+mAmount.value)return alert('Informe um valor');const obj={amount:+mAmount.value,hours:+mHours.value||0,date:mDate.value,note:mNote.value};if(id){Object.assign(data.incomes.find(x=>x.id==id),obj)}else data.incomes.push({id:uid(),...obj});save();closeModal()}
function openExpense(existing){const x=existing||{};const opts=data.bills.map(b=>`<option value="${b.id}" ${x.billId==b.id?'selected':''}>${esc(b.name)} — ${money(b.amount-b.paidAmount)}</option>`).join('');openModal(`<h2>${existing?'Editar gasto':'Registrar gasto'}</h2><label>Categoria<select id="mCategory"><option>Gasolina</option><option>Alimentação</option><option>Casa</option><option>Carro</option><option>Faculdade</option><option>Saúde</option><option>Outro</option></select></label><label>Valor<input id="mAmount" type="number" value="${x.amount||''}"></label><label>Data<input id="mDate" type="date" value="${x.date||selected()}"></label><label>Tratamento do gasto<select id="mPlan"><option value="budget" ${x.plannedType==='budget'?'selected':''}>Consumir orçamento existente</option><option value="adjust" ${x.plannedType==='adjust'?'selected':''}>Adicionar ao orçamento</option><option value="extra" ${x.plannedType==='extra'?'selected':''}>Não programado / extra</option></select></label><label>Vincular pagamento a conta (opcional)<select id="mBill"><option value="">Nenhuma</option>${opts}</select></label><label>Observação<input id="mNote" value="${esc(x.note||'')}"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveExpense(${existing?x.id:''})">Salvar</button></div>`);mCategory.value=x.category||'Outro';}
function saveExpense(id){if(!+mAmount.value)return alert('Informe um valor');const obj={amount:+mAmount.value,date:mDate.value,category:mCategory.value,plannedType:mPlan.value,billId:mBill.value?+mBill.value:null,note:mNote.value};if(id){const old=data.expenses.find(x=>x.id==id);if(old?.billId&&old.billId!==obj.billId)rebuildBillPayments();Object.assign(old,obj)}else data.expenses.push({id:uid(),...obj});applyBudgetEffect(obj,id);rebuildBillPayments();save();closeModal()}
function applyBudgetEffect(e,id){if(e.plannedType==='extra')return;let b=data.budgets.find(x=>x.category===e.category);if(!b){b={id:uid(),category:e.category,planned:0,adjustments:0};data.budgets.push(b)}if(e.plannedType==='adjust')b.adjustments+=Number(e.amount||0)}
function rebuildBillPayments(){data.bills.forEach(b=>{b.paidAmount=0;b.history=[];b.paymentPlan??={type:'single',installments:[]};b.paymentPlan.installments??=[];b.paymentPlan.installments.forEach(i=>i.paidAmount=0)});data.expenses.filter(e=>e.billId).forEach(e=>{const b=data.bills.find(x=>x.id===e.billId);if(b){const amount=Number(e.amount||0);b.paidAmount+=amount;b.history.push({id:e.id,amount,date:e.date,note:e.note||'Pagamento vinculado',installmentId:e.installmentId||null});if(e.installmentId){const i=b.paymentPlan.installments.find(x=>x.id===Number(e.installmentId));if(i)i.paidAmount+=amount}}});data.bills.forEach(b=>b.paid=b.paidAmount>=Number(b.amount||0))}
function extraExpenses(){return sum(data.expenses.filter(x=>x.plannedType==='extra'),x=>x.amount)}
function editEntry(t,id){const x=data[t==='income'?'incomes':'expenses'].find(x=>x.id==id);t==='income'?openIncome(x):openExpense(x)}
function deleteEntry(t,id){if(confirm('Excluir este registro?')){const k=t==='income'?'incomes':'expenses';data[k]=data[k].filter(x=>x.id!=id);rebuildBillPayments();save()}}
function openStudy(){openModal(`<h2>Registrar estudo</h2><label>Horas<input id="mHours" type="number" step=".5"></label><label>Data<input id="mDate" type="date" value="${selected()}"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveStudy()">Salvar</button></div>`)}function saveStudy(){if(!+mHours.value)return alert('Informe as horas');data.study.push({id:uid(),hours:+mHours.value,date:mDate.value});save();closeModal()}function addStudy(h){data.study.push({id:uid(),hours:h,date:selected()});save()}
function setQuality(t,v){data.quality[selected()]??={};data.quality[selected()][t]=v;save()}
function toggleActivity(date,id){const a=dayPlan(date).find(x=>String(x.id)===String(id));if(!a)return;if(id.startsWith('base-')){data.plannedActivityOverrides[date]??={};data.plannedActivityOverrides[date][id]??={};data.plannedActivityOverrides[date][id].done=!a.done}else{const x=(data.dailyActivities[date]||[]).find(x=>String(x.id)===String(id));if(x)x.done=!x.done}save()}
function deleteActivity(date,id){if(!confirm('Excluir esta atividade?'))return;const a=dayPlan(date).find(x=>String(x.id)===String(id));if(!a)return;if(a.weekly||id.startsWith('base-')){data.plannedActivityOverrides[date]??={};data.plannedActivityOverrides[date][id]??={};data.plannedActivityOverrides[date][id].removed=true;}else{data.dailyActivities[date]=(data.dailyActivities[date]||[]).filter(x=>String(x.id)!==String(id));}save()}
function editActivity(date,id){const a=dayPlan(date).find(x=>String(x.id)===String(id));if(!a)return;openModal(`<h2>Editar programação</h2><label>Nome<input id="mActName" value="${esc(a.name)}"></label><label>Tipo de métrica<select id="mActMetric"><option value="money">Meta financeira (R$)</option><option value="hours">Tempo (horas)</option><option value="check">Conclusão</option></select></label><label>Meta<input id="mActTarget" type="number" step="0.5" value="${a.target??''}"></label><p class="muted">Para trabalho, a meta é financeira. Para estudo, a meta é tempo. O resultado real vem dos registros de ganhos/estudos.</p><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveActivityEdit('${date}','${esc(id)}')">Salvar</button></div>`);mActMetric.value=a.metric}
function saveActivityEdit(date,id){const o=data.plannedActivityOverrides[date]??={};data.plannedActivityOverrides[date]=o;o[id]={name:mActName.value,metric:mActMetric.value,target:Number(mActTarget.value)||0,done:(o[id]?.done||false)};if(id.startsWith('base-')&&mActMetric.value==='money')o.workTarget=Number(mActTarget.value)||0;save();closeModal()}
function editWeeklyTargets(){const names=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];const rows=names.map((n,i)=>`<label>${n}<input id="w${i}" type="number" step="1000" value="${Number(data.weeklyWorkTargets?.[i]??plannedGoalsByDay[i]??0)}"></label>`).join('');openModal(`<h2>Metas financeiras por dia da semana</h2><p class="muted">Altere o valor padrão de cada dia. Segunda pode ficar em R$ 0 se você não trabalha. Alterações feitas aqui valem para as datas sem uma meta específica.</p>${rows}<div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveWeeklyTargets()">Salvar e recalcular</button></div>`)}
function saveWeeklyTargets(){data.weeklyWorkTargets={0:+w0.value||0,1:+w1.value||0,2:+w2.value||0,3:+w3.value||0,4:+w4.value||0,5:+w5.value||0,6:+w6.value||0};save();closeModal()}
function openRedistribute(){const gap=planningGap();if(Math.abs(gap)<0.5)return;const direction=gap>0?'aumentar':'reduzir';const candidates=futureWorkDates().filter(d=>d!==selected());const byDow=[0,1,2,3,4,5,6].map(i=>({i,dates:candidates.filter(d=>new Date(d+'T12:00').getDay()===i)})).filter(x=>x.dates.length);const names=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];const checks=byDow.map(x=>`<label class="checkrow"><span><input type="checkbox" name="redistDow" value="${x.i}"> ${names[x.i]} (${x.dates.length} restante(s))</span><b>${money(sum(x.dates,d=>plannedGoalFor(d)))} planejado</b></label>`).join('');const dateOpts=candidates.map(d=>`<option value="${d}">${formatDate(d)} — ${names[new Date(d+'T12:00').getDay()]} — ${money(plannedGoalFor(d))}</option>`).join('');openModal(`<h2>Redistribuir ${money(Math.abs(gap))}</h2><p class="muted">O planejamento precisa ${direction} ${money(Math.abs(gap))}. Você escolhe onde colocar esse valor. O app só faz a conta.</p><h3>Opção 1 — Distribuir igualmente por dias da semana</h3>${checks||'<p class="muted">Não há outros dias de trabalho no ciclo.</p>'}<div class="formActions"><button onclick="redistributeByWeekday(${gap})">Aplicar aos dias marcados</button></div><h3>Opção 2 — Colocar em uma data específica</h3><label>Data<select id="mRedistDate">${dateOpts}</select></label><div class="formActions"><button class="success" onclick="redistributeSpecific(${gap})">Adicionar à data escolhida</button></div>`)}
function redistributeByWeekday(gap){const checked=[...document.querySelectorAll('input[name=redistDow]:checked')].map(x=>+x.value);if(!checked.length)return alert('Escolha pelo menos um dia da semana.');const dates=futureWorkDates().filter(d=>checked.includes(new Date(d+'T12:00').getDay()));if(!dates.length)return alert('Não há datas restantes para essa escolha.');const each=gap/dates.length;dates.forEach(d=>{data.plannedActivityOverrides[d]??={};data.plannedActivityOverrides[d].workTarget=Math.max(0,plannedGoalFor(d)+each)});save();closeModal()}
function redistributeSpecific(gap){const d=mRedistDate.value;if(!d)return;data.plannedActivityOverrides[d]??={};data.plannedActivityOverrides[d].workTarget=Math.max(0,plannedGoalFor(d)+gap);save();closeModal()}
function addCustomActivity(){openModal(`<h2>Adicionar atividade ao dia</h2><label>Nome<input id="mActName"></label><label>Tipo<select id="mActMetric"><option value="check">Conclusão</option><option value="hours">Horas</option><option value="money">Meta financeira</option></select></label><label>Meta<input id="mActTarget" type="number" step="0.5"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveCustomActivity()">Adicionar</button></div>`)}function saveCustomActivity(){data.dailyActivities[selected()]??=[];data.dailyActivities[selected()].push({id:'custom-'+uid(),icon:'📌',name:mActName.value,metric:mActMetric.value,target:Number(mActTarget.value)||0,done:false});save();closeModal()}
function editWeeklyActivities(){const names=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];openModal(`<h2>Configurar rotina semanal</h2><p class="muted">Escolha um dia e defina quais atividades acontecem nele. Isso controla a programação padrão; você ainda pode alterar uma data específica.</p><label>Dia da semana<select id="mWeekDay" onchange="renderWeeklyEditor()">${names.map((n,i)=>`<option value="${i}">${n}</option>`).join('')}</select></label><div id="weeklyEditor"></div><div class="formActions"><button onclick="closeModal()">Fechar</button></div></div>`);renderWeeklyEditor()}
function renderWeeklyEditor(){const dow=Number(document.getElementById('mWeekDay')?.value||0),items=data.weeklyActivities?.[dow]||[];const el=document.getElementById('weeklyEditor');if(!el)return;el.innerHTML=items.map((a,i)=>`<div class="billRow"><div><strong>${esc(a.icon||'📌')} ${esc(a.name)}</strong><small>${a.metric==='money'?'Meta financeira: '+money(a.target||0):a.metric==='hours'?'Meta: '+(a.target||0)+'h':'Atividade de conclusão'}</small></div><div><button onclick="editWeeklyItem(${dow},${i})">Editar</button><button class="danger" onclick="removeWeeklyItem(${dow},${i})">Excluir</button></div></div>`).join('')||'<p class="muted">Nenhuma atividade neste dia.</p>';el.insertAdjacentHTML('beforeend',`<button onclick="addWeeklyItem(${dow})">+ Adicionar atividade</button>`)}
function addWeeklyItem(dow){openModal(`<h2>Adicionar atividade — ${['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'][dow]}</h2><label>Ícone<input id="mWIcon" value="📌"></label><label>Nome<input id="mWName"></label><label>Tipo<select id="mWMetric"><option value="check">Conclusão</option><option value="hours">Horas</option><option value="money">Meta financeira</option></select></label><label>Meta<input id="mWTarget" type="number" step="0.5"></label><div class="formActions"><button onclick="editWeeklyActivities()">Voltar</button><button class="success" onclick="saveWeeklyItem(${dow},null)">Salvar</button></div>`)}
function editWeeklyItem(dow,i){const a=data.weeklyActivities[dow][i];openModal(`<h2>Editar atividade</h2><label>Ícone<input id="mWIcon" value="${esc(a.icon||'📌')}"></label><label>Nome<input id="mWName" value="${esc(a.name||'')}"></label><label>Tipo<select id="mWMetric"><option value="check">Conclusão</option><option value="hours">Horas</option><option value="money">Meta financeira</option></select></label><label>Meta<input id="mWTarget" type="number" step="0.5" value="${a.target??''}"></label><div class="formActions"><button onclick="editWeeklyActivities()">Voltar</button><button class="success" onclick="saveWeeklyItem(${dow},${i})">Salvar</button></div>`);mWMetric.value=a.metric||'check'}
function saveWeeklyItem(dow,i){const item={id:i==null?'base-'+dow+'-'+uid():data.weeklyActivities[dow][i].id,icon:mWIcon.value||'📌',name:mWName.value.trim(),metric:mWMetric.value,target:Number(mWTarget.value)||0};if(!item.name)return alert('Informe o nome');data.weeklyActivities[dow]??=[];if(i==null)data.weeklyActivities[dow].push(item);else data.weeklyActivities[dow][i]=item;save();editWeeklyActivities()}
function removeWeeklyItem(dow,i){if(!confirm('Excluir esta atividade deste dia da semana?'))return;data.weeklyActivities[dow].splice(i,1);save();renderWeeklyEditor()}
function closeDay(date){if(!date)return;data.dayStatus[date]={closed:true,closedAt:new Date().toISOString()};save()}
function reopenDay(date){if(!date)return;delete data.dayStatus[date];save()}
function addReminder(){openModal(`<h2>Novo lembrete</h2><label>Título<input id="mTitle"></label><label>Data<input id="mDate" type="date" value="${selected()}"></label><label>Avisar quantos dias antes?<input id="mBefore" type="number" value="5"></label><label>Importância<select id="mImportance"><option>Normal</option><option>Importante</option><option>Urgente</option></select></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveReminder()">Salvar</button></div>`)}function saveReminder(){if(!mTitle.value||!mDate.value)return alert('Preencha título e data');data.reminders.push({id:uid(),title:mTitle.value,date:mDate.value,before:+mBefore.value||0,importance:mImportance.value,done:false});save();closeModal()}function reminderHTML(r){return `<div class="reminderRow"><div><strong>${esc(r.title)}</strong><small>${formatDate(r.date)} • ${r.importance}</small></div><button onclick="toggleReminder(${r.id})">Concluir</button></div>`}function toggleReminder(id){const x=data.reminders.find(x=>x.id==id);x.done=!x.done;save()}
function billStatus(b){if(b.paid)return {text:'✓ Paga',cls:'paidBadge'};const diff=Math.ceil((new Date(b.due+'T12:00')-new Date(localISO()+'T12:00'))/86400000);return diff<0?{text:'🔴 Vencida',cls:'unpaidBadge'}:diff<=5?{text:'🟠 Vence em breve',cls:'unpaidBadge'}:{text:'⚪ Futura',cls:'unpaidBadge'}}
function paymentPlanTypeLabel(b){const t=b.paymentPlan?.type||'single';return t==='installments'?'Parcelas':t==='recurring'?'Recorrente':'Pagamento único'}
function installmentOutstanding(b,i){return Math.max(0,Number(i.amount||0)-Number(i.paidAmount||0))}
function billPlanSummary(b){const p=b.paymentPlan||{type:'single',installments:[]};if(p.type==='single')return 'Pagamento único';const items=p.installments||[];if(!items.length)return p.type==='recurring'?'Recorrente sem parcelas geradas':'Parcelas não configuradas';const open=sum(items,i=>installmentOutstanding(b,i));const next=items.find(i=>installmentOutstanding(b,i)>0);return `${p.type==='recurring'?'Recorrente':'Parcelas'} • ${items.length} previsto(s)${next?' • próxima '+formatDate(next.due):''} • pendente no plano ${money(open)}`}
function renderBills(){const el=document.getElementById('billList');if(!el)return;const bills=[...data.bills].sort((a,b)=>(a.due||'').localeCompare(b.due||''));el.innerHTML=bills.map(b=>{const s=billStatus(b),open=Math.max(0,Number(b.amount||0)-Number(b.paidAmount||0));return `<div class="billRow"><div><strong>🧾 ${esc(b.name)}</strong><small>${money(b.amount)} • pago ${money(b.paidAmount)} • restante ${money(open)} • ${formatDate(b.due)}<br>${esc(billPlanSummary(b))}</small></div><div>${open>0?`<button class="success" onclick="openPaymentModal(${b.id})">💳 Realizar pagamento</button>`:`<span class="paidBadge">✓ Quitada</span>`}<button onclick="editBill(${b.id})">Editar</button><button class="danger" onclick="deleteBill(${b.id})">Excluir</button><br><span class="${s.cls}">${s.text}</span></div></div>`}).join('')||'<div class="muted">Nenhuma conta neste ciclo. Adicione uma conta para que ela passe a compor automaticamente a meta.</div>'}
function openPaymentModal(id){const b=data.bills.find(x=>x.id==id);if(!b)return;const remaining=Math.max(0,Number(b.amount||0)-Number(b.paidAmount||0));const items=(b.paymentPlan?.installments||[]).filter(i=>installmentOutstanding(b,i)>0);const opts=items.length?`<label>Vincular a parcela<select id="mInstallment"><option value="">Pagamento geral da conta</option>${items.map((i,n)=>`<option value="${i.id}">Parcela ${n+1} — ${money(i.amount)} — ${formatDate(i.due)} — falta ${money(installmentOutstanding(b,i))}</option>`).join('')}</select></label>`:'';openModal(`<h2>💳 Realizar pagamento</h2><p><b>${esc(b.name)}</b><br><span class="muted">Pendente: ${money(remaining)}</span></p><label>Valor do pagamento<input id="mAmount" type="number" min="1" max="${remaining}" value="${remaining}"></label>${opts}<label>Data<input id="mDate" type="date" value="${selected()}"></label><label>Categoria<select id="mCategory"><option>Gasolina</option><option>Alimentação</option><option>Casa</option><option>Carro</option><option>Faculdade</option><option>Saúde</option><option>Outro</option></select></label><label>Tratamento do gasto<select id="mPlan"><option value="budget">Consumir orçamento existente</option><option value="adjust">Adicionar ao orçamento</option><option value="extra">Não programado / extra</option></select></label><label>Observação<input id="mNote" placeholder="Ex.: pagamento parcial"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="savePayment(${b.id})">Registrar pagamento</button></div>`)}
function savePayment(billId){const b=data.bills.find(x=>x.id==billId);if(!b)return;const amount=Number(mAmount.value||0),remaining=Math.max(0,Number(b.amount||0)-Number(b.paidAmount||0));if(amount<=0)return alert('Informe um valor válido');if(amount>remaining)return alert('O pagamento não pode ser maior que o valor pendente.');if(!mDate.value)return alert('Informe a data.');const installmentId=typeof mInstallment!=='undefined'&&mInstallment.value?Number(mInstallment.value):null;if(installmentId){const inst=(b.paymentPlan?.installments||[]).find(i=>i.id===installmentId);if(inst&&amount>installmentOutstanding(b,inst))return alert('O pagamento não pode ser maior que o restante da parcela selecionada.')}const obj={id:uid(),amount,date:mDate.value,category:mCategory.value,plannedType:mPlan.value,billId,installmentId,note:mNote.value||('Pagamento de '+b.name)};data.expenses.push(obj);applyBudgetEffect(obj);rebuildBillPayments();save();closeModal()}
function addBill(){openBillModal()}function editBill(id){openBillModal(data.bills.find(x=>x.id==id))}
function openBillModal(b){const p=b?.paymentPlan||{type:'single',installments:[]};openModal(`<h2>${b?'Editar conta':'Nova conta'}</h2><label>Nome<input id="mName" value="${esc(b?.name||'')}"></label><label>Valor total da conta<input id="mAmount" type="number" value="${b?.amount||''}"></label><label>Primeiro vencimento / vencimento<input id="mDate" type="date" value="${b?.due||selected()}"></label><label>Forma de pagamento planejada<select id="mPlanType" onchange="renderPaymentPlanEditor()"><option value="single" ${p.type==='single'?'selected':''}>Pagamento único</option><option value="installments" ${p.type==='installments'?'selected':''}>Parcelas com datas/valores definidos</option><option value="recurring" ${p.type==='recurring'?'selected':''}>Recorrente (gerar parcelas)</option></select></label><div id="paymentPlanEditor"></div><label>Observação<input id="mBillNote" value="${esc(b?.note||'')}"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="${b?'saveBillEdit('+b.id+')':'saveBill()'}">Salvar</button></div>`);renderPaymentPlanEditor(b)}
function renderPaymentPlanEditor(existing){const type=document.getElementById('mPlanType')?.value||existing?.paymentPlan?.type||'single',p=existing?.paymentPlan||{type:'single',installments:[]},el=document.getElementById('paymentPlanEditor');if(!el)return;if(type==='single'){el.innerHTML='<p class="muted">A conta será quitada por pagamentos livres. Você ainda pode pagar parcialmente quantas vezes precisar.</p>';return}if(type==='installments'){const items=p.installments?.length?p.installments:[{id:uid(),amount:0,due:document.getElementById('mDate')?.value||selected()}];el.innerHTML=`<div id="installmentRows">${items.map((i,n)=>`<div class="planRow" data-id="${i.id}"><div><b>Parcela ${n+1}</b><input class="pAmount" type="number" step="0.01" placeholder="Valor" value="${i.amount||''}"><input class="pDue" type="date" value="${i.due||selected()}"></div><button type="button" class="danger" onclick="this.parentElement.remove()">Excluir</button></div>`).join('')}</div><button type="button" onclick="addInstallmentRow()">+ Adicionar parcela</button><p class="muted">Você pode definir valores e datas diferentes para cada parcela. A soma planejada pode ser igual ou diferente do total; o total da conta continua sendo a fonte da meta.</p>`;return}el.innerHTML=`<label>Periodicidade<select id="mRecFreq"><option value="weekly">Semanal</option><option value="biweekly">A cada 2 semanas</option><option value="monthly">Mensal</option></select></label><label>Valor por ocorrência<input id="mRecAmount" type="number" value="${p.recurring?.amount||''}"></label><label>Data inicial<input id="mRecStart" type="date" value="${p.recurring?.start||existing?.due||selected()}"></label><label>Data final<input id="mRecEnd" type="date" value="${p.recurring?.end||data.periodEnd}"></label><label>Dia da semana (para semanal)<select id="mRecWeekday">${['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'].map((n,i)=>`<option value="${i}" ${Number(p.recurring?.weekday??3)===i?'selected':''}>${n}</option>`).join('')}</select></label><p class="muted">Para toda quarta-feira, escolha Semanal e Quarta.</p>`;if(p.recurring?.frequency)document.getElementById('mRecFreq').value=p.recurring.frequency}
function addInstallmentRow(){const rows=document.getElementById('installmentRows');if(!rows)return;const n=rows.children.length+1;rows.insertAdjacentHTML('beforeend',`<div class="planRow" data-id="${uid()}"><div><b>Parcela ${n}</b><input class="pAmount" type="number" step="0.01" placeholder="Valor"><input class="pDue" type="date" value="${selected()}"></div><button type="button" class="danger" onclick="this.parentElement.remove()">Excluir</button></div>`)}
function collectPaymentPlan(existing){const type=document.getElementById('mPlanType')?.value||'single';if(type==='single')return {type:'single',installments:[]};if(type==='installments'){const old=existing?.paymentPlan?.installments||[],rows=[...document.querySelectorAll('#installmentRows .planRow')],installments=rows.map(r=>{const id=Number(r.dataset.id)||uid(),prev=old.find(x=>x.id===id);return {id,amount:Number(r.querySelector('.pAmount')?.value||0),due:r.querySelector('.pDue')?.value||selected(),paidAmount:Number(prev?.paidAmount||0)}}).filter(x=>x.amount>0&&x.due);if(!installments.length)return alert('Adicione pelo menos uma parcela com valor e data.'),null;return {type:'installments',installments}}const freq=document.getElementById('mRecFreq').value,amount=Number(document.getElementById('mRecAmount').value||0),start=document.getElementById('mRecStart').value,end=document.getElementById('mRecEnd').value,weekday=Number(document.getElementById('mRecWeekday').value);if(amount<=0||!start||!end||end<start)return alert('Preencha corretamente o plano recorrente.'),null;const old=existing?.paymentPlan?.installments||[],oldByDate=new Map(old.map(x=>[x.due,x])),installments=[],d=new Date(start+'T12:00');if(freq==='weekly'||freq==='biweekly'){while(d.toISOString().slice(0,10)<=end){if(d.getDay()===weekday){const due=d.toISOString().slice(0,10),prev=oldByDate.get(due);installments.push({id:prev?.id||uid(),amount,due,paidAmount:Number(prev?.paidAmount||0)});d.setDate(d.getDate()+(freq==='weekly'?7:14))}else d.setDate(d.getDate()+1)}}else{const day=new Date(start+'T12:00').getDate(),cur=new Date(start+'T12:00');while(cur.toISOString().slice(0,10)<=end){const due=cur.toISOString().slice(0,10),prev=oldByDate.get(due);installments.push({id:prev?.id||uid(),amount,due,paidAmount:Number(prev?.paidAmount||0)});cur.setMonth(cur.getMonth()+1);if(cur.getDate()!==day)cur.setDate(0)}}if(!installments.length)return alert('Nenhuma ocorrência foi gerada com essas datas.'),null;return {type:'recurring',recurring:{frequency:freq,amount,start,end,weekday},installments}}
function saveBill(){if(!mName.value||!+mAmount.value||!mDate.value)return alert('Preencha nome, valor e vencimento');const plan=collectPaymentPlan();if(!plan)return;data.bills.push({id:uid(),name:mName.value,amount:+mAmount.value,due:mDate.value,note:mBillNote.value,paidAmount:0,paid:false,history:[],paymentPlan:plan});recalcGoal();save();closeModal()}
function saveBillEdit(id){const b=data.bills.find(x=>x.id==id);if(!b)return;const plan=collectPaymentPlan(b);if(!plan)return;Object.assign(b,{name:mName.value,amount:+mAmount.value,due:mDate.value,note:mBillNote.value,paymentPlan:plan});rebuildBillPayments();recalcGoal();save();closeModal()}
function deleteBill(id){if(confirm('Excluir esta conta? Ela sairá da composição da meta deste ciclo. Os pagamentos vinculados serão desvinculados, mas permanecem no histórico de gastos.')){data.bills=data.bills.filter(x=>x.id!=id);data.expenses.forEach(e=>{if(e.billId==id){e.billId=null;e.installmentId=null}});recalcGoal();save()}}
function renderFinancialOverview(){const el=document.getElementById('financialOverview');if(!el)return;const pending=data.bills.filter(b=>Math.max(0,Number(b.amount||0)-Number(b.paidAmount||0))>0),pendingTotal=sum(pending,b=>Math.max(0,Number(b.amount||0)-Number(b.paidAmount||0))),paidTotal=sum(data.bills,b=>Number(b.paidAmount||0)),accountTotal=sum(data.bills,b=>Number(b.amount||0)),closedDeficit=closedPlanDeficit(),list=pending.slice(0,3).map(b=>esc(b.name)+' — '+money(Math.max(0,b.amount-b.paidAmount))).join(' • ');el.innerHTML='<div class="analyticsCards"><div><small>Contas pendentes</small><strong>'+money(pendingTotal)+'</strong></div><div><small>Pagamentos registrados</small><strong>'+money(paidTotal)+'</strong></div><div><small>Valor das contas do ciclo</small><strong>'+money(accountTotal)+'</strong></div><div><small>Falta ganhar para a meta</small><strong>'+money(Math.max(0,Number(data.goal||0)-incomeTotal()))+'</strong></div><div><small>Déficit dos dias concluídos</small><strong>'+money(closedDeficit)+'</strong></div></div><div class="summaryLine">'+(pending.length?'<b>Próximas contas:</b> '+list:'🟢 Nenhuma conta pendente.')+'</div><div class="muted" style="margin-top:8px">As contas deste ciclo são a única base financeira da meta. O valor total das contas + margem de segurança = meta do ciclo. Pagamentos reduzem o saldo pendente, mas não reduzem o valor original da meta.</div>'}
function renderObligations(){const el=document.getElementById('obligationList');if(!el)return;const sumEl=document.getElementById('obligationSummary');if(sumEl)sumEl.innerHTML=`As contas cadastradas abaixo compõem automaticamente a meta. Total das contas: <b>${money(sum(data.bills,b=>b.amount))}</b> • Margem: <b>${money(data.safetyMargin)}</b> • <b>Meta geral: ${money(data.goal)}</b>`;el.innerHTML='<div class="muted">Esta versão usa um único cadastro financeiro: <b>Contas e pagamentos</b>. Não existem obrigações separadas. Adicione ou edite uma conta na seção abaixo; a meta será recalculada automaticamente.</div>'}
function renderBudgets(){const el=document.getElementById('budgetList');if(!el)return;const cats=['Gasolina','Alimentação','Casa','Carro','Faculdade','Saúde','Outro'];el.innerHTML=cats.map(c=>{let b=data.budgets.find(x=>x.category===c);const planned=Number(b?.planned||0)+Number(b?.adjustments||0),spent=sum(data.expenses.filter(e=>e.category===c&&e.plannedType!=='extra'),e=>e.amount);return `<div class="budgetRow"><div><strong>${c}</strong><small>Orçamento ${money(planned)} • gasto ${money(spent)} • restante ${money(Math.max(0,planned-spent))}</small></div><button onclick="editBudget('${c}')">Editar</button></div>`}).join('')}
function editBudget(cat){const b=data.budgets.find(x=>x.category===cat)||{planned:0,adjustments:0};openModal(`<h2>Orçamento: ${esc(cat)}</h2><label>Valor planejado inicial<input id="mBudget" type="number" value="${b.planned||0}"></label><p class="muted">Ajustes feitos durante o ciclo são preservados separadamente.</p><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveBudget('${esc(cat)}')">Salvar</button></div>`)}function saveBudget(cat){let b=data.budgets.find(x=>x.category===cat);if(!b){b={id:uid(),category:cat,planned:0,adjustments:0};data.budgets.push(b)}b.planned=Number(mBudget.value)||0;save();closeModal()}
function renderAnalytics(){const el=document.getElementById('analyticsContent');if(!el)return;const g=incomeTotal(),e=expenseTotal(),extra=extraExpenses(),billed=sum(data.bills,x=>Math.max(0,x.amount-x.paidAmount)),progress=data.goal?Math.min(100,g/data.goal*100):0;const byCat={};data.expenses.forEach(x=>byCat[x.category]=(byCat[x.category]||0)+x.amount);const max=Math.max(1,...Object.values(byCat));const bars=Object.entries(byCat).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="barLine"><span>${esc(k)}</span><div><i style="width:${v/max*100}%"></i></div><b>${money(v)}</b></div>`).join('');const days=Math.max(1,daysBetween(data.periodStart,localISO()>data.periodEnd?data.periodEnd:localISO()));const requiredPerDay=Math.ceil(Math.max(0,data.goal-g)/Math.max(1,cycleDaysRemaining()));el.innerHTML=`<div class="analyticsCards"><div><small>Progresso da meta</small><strong>${progress.toFixed(1)}%</strong></div><div><small>Receita</small><strong>${money(g)}</strong></div><div><small>Despesas</small><strong>${money(e)}</strong></div><div><small>Extras</small><strong>${money(extra)}</strong></div><div><small>Contas pendentes</small><strong>${money(billed)}</strong></div><div><small>Necessário/dia</small><strong>${money(requiredPerDay)}</strong></div></div><div class="panel"><h3>Despesas por categoria</h3>${bars||'<span class="muted">Sem despesas.</span>'}</div><div class="panel"><h3>Leitura do ciclo</h3><p>${progress>=100?'🟢 Meta financeira atingida.':requiredPerDay? 'Você precisa manter aproximadamente '+money(requiredPerDay)+' por dia restante para atingir a meta.':'Sem necessidade financeira adicional calculada.'}</p><p class="muted">Extras não programados: ${money(extra)}. Contas ainda abertas: ${money(billed)}.</p></div>`}
function cycleSnapshot(){return {id:data.cycleId,name:data.cycleName,start:data.periodStart,end:data.periodEnd,goal:data.goal,safetyMargin:data.safetyMargin,income:incomeTotal(),expense:expenseTotal(),closed:true,pending:sum(data.bills,b=>Math.max(0,b.amount-b.paidAmount)),bills:JSON.parse(JSON.stringify(data.bills)),incomes:JSON.parse(JSON.stringify(data.incomes)),expenses:JSON.parse(JSON.stringify(data.expenses))}}
function renderCycles(){const el=document.getElementById('cycleHistory');if(!el)return;const current={id:data.cycleId,name:data.cycleName,start:data.periodStart,end:data.periodEnd,goal:data.goal,income:incomeTotal(),expense:expenseTotal(),closed:false,pending:sum(data.bills,b=>Math.max(0,b.amount-b.paidAmount)),bills:data.bills},all=[...data.cycles,current].sort((a,b)=>b.start.localeCompare(a.start));el.innerHTML=all.map(c=>{const count=(c.bills||[]).length,pending=Number(c.pending||0);return `<div class="cycleRow"><div><strong>${esc(c.name||'Ciclo')}</strong><small>${formatDate(c.start)} → ${formatDate(c.end)} • ${count} conta(s)${pending?` • pendente ${money(pending)}`:''}</small></div><div><strong>${money(c.income||0)}</strong><small>Meta ${money(c.goal||0)} • ${c.closed?'Encerrado':'Em andamento'}</small></div></div>`}).join('')||'<div class="muted">Nenhum ciclo registrado.</div>'}
function renderSettings(){const el=document.getElementById('financialSettings');if(el)el.innerHTML=`<div class="summaryLine"><b>${esc(data.cycleName)}</b><br>Meta: ${money(data.goal)}<br>Contas: ${money(sum(data.bills,b=>b.amount))}<br>Margem: ${money(data.safetyMargin)}<br>Período: ${formatDate(data.periodStart)} → ${formatDate(data.periodEnd)}</div>`}
function newCycle(){const pending=data.bills.filter(b=>Number(b.amount||0)>Number(b.paidAmount||0)),options=pending.map(b=>`<label class="checkrow"><span><input type="checkbox" name="carryBill" value="${b.id}" checked> ${esc(b.name)}</span><b>${money(Math.max(0,b.amount-b.paidAmount))}</b></label>`).join('');openModal(`<h2>Novo ciclo</h2><label>Nome do ciclo<input id="mCycleName" value="Ciclo ${formatDate(data.periodEnd)} → novo"></label><label>Início<input id="mStart" type="date" value="${data.periodEnd}"></label><label>Fim<input id="mEnd" type="date" value="${data.periodEnd}"></label><label>Margem de segurança<input id="mMargin" type="number" value="${data.safetyMargin||100000}"></label><h3>Carregar contas pendentes</h3><p class="muted">O ciclo atual será fechado com seu histórico intacto. Marque apenas as contas que deseja levar ao novo ciclo. O novo ciclo receberá o valor que ainda falta pagar, e você poderá editar cada conta depois.</p><div>${options||'<div class="muted">Nenhuma conta pendente para carregar.</div>'}</div><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="createCycle()">Fechar atual e criar</button></div>`)}
function createCycle(){const selected=[...document.querySelectorAll('input[name=carryBill]:checked')].map(x=>Number(x.value)),currentSnapshot=cycleSnapshot(),carried=data.bills.filter(b=>selected.includes(b.id)).map(b=>{const remaining=Math.max(0,Number(b.amount||0)-Number(b.paidAmount||0)),copy={...JSON.parse(JSON.stringify(b)),id:uid(),amount:remaining,paidAmount:0,paid:false,history:[],note:(b.note?b.note+' • ':'')+'Carregada do ciclo anterior'};if(copy.paymentPlan?.installments)copy.paymentPlan.installments=copy.paymentPlan.installments.map(i=>({...i,id:uid(),amount:Number(i.amount||0),paidAmount:0}));return copy});data.cycles.push(currentSnapshot);const start=mStart.value||data.periodEnd,endDate=mEnd.value;if(!endDate||endDate<start)return alert('A data final deve ser igual ou posterior à data inicial.');data={...initial,version:15,cycleId:uid(),cycleName:mCycleName.value||'Novo ciclo',periodStart:start,periodEnd:endDate,safetyMargin:+mMargin.value||0,selectedDate:start,incomes:[],expenses:[],study:[],quality:{},reminders:[],dailyActivities:{},bills:carried,budgets:[],cycles:data.cycles,plannedActivityOverrides:{},weeklyActivities:data.weeklyActivities};recalcGoal();save();closeModal()}
function openFinancialSettings(){openModal(`<h2>Editar ciclo atual</h2><label>Nome<input id="mCycleName" value="${esc(data.cycleName)}"></label><label>Margem de segurança<input id="mMargin" type="number" value="${data.safetyMargin}"></label><label>Início<input id="mStart" type="date" value="${data.periodStart}"></label><label>Fim<input id="mEnd" type="date" value="${data.periodEnd}"></label><p class="muted">A meta geral é calculada automaticamente: soma do valor total das contas deste ciclo + margem de segurança. Para alterar a meta pela base financeira, edite, adicione ou exclua contas.</p><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveFinancialSettings()">Salvar</button></div>`)}
function saveFinancialSettings(){if(!mCycleName.value||!mStart.value||!mEnd.value)return alert('Preencha nome e período.');if(mEnd.value<mStart.value)return alert('A data final deve ser igual ou posterior à inicial.');data.cycleName=mCycleName.value;data.safetyMargin=+mMargin.value||0;data.periodStart=mStart.value;data.periodEnd=mEnd.value;recalcGoal();save();closeModal()}
function exportBackup(){data.lastBackup=localISO();localStorage.setItem(KEY,JSON.stringify(data));const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='backup-minha-meta-v15-'+localISO()+'.json';a.click();URL.revokeObjectURL(a.href)}
function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);normalize();save();alert('Backup importado com sucesso na versão 15.')}catch{alert('Arquivo inválido')}};r.readAsText(f)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
render();
