const KEY='minha_meta_v14';
const fmt=n=>new Intl.NumberFormat('es-AR',{maximumFractionDigits:0}).format(Math.round(Number(n||0)));
const money=n=>'$ '+fmt(n);
const signed=n=>(n>=0?'+':'−')+money(Math.abs(n));
const localISO=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const brl=v=>Math.round(v*301);
const initialBills=[
 ['Aluguel',brl(1071),'2026-10-04','Valor informado em reais'],['Santander Argentina',brl(3032.26),'2026-10-02','Valor estimado'],['Santander Brasil',brl(123.90),'2026-09-10',''],['Tênis – parcela 1',brl(200),'2026-09-09',''],['Tênis – parcela 2',brl(200),'2026-09-23',''],['Luz, internet e água',brl(350),'2026-09-14','Aproximado'],['Curso Médio Fácil',brl(100),'2026-09-09',''],['Comida + gasolina',brl(2500),'2026-10-05','Orçamento aproximado do período'],['Futebol',brl(80),'2026-10-05','Aproximadamente R$20 por semana'],['Hospedagem do Thor',brl(664),'2026-10-05','Pagamentos semanais aproximados de $50.000'],['Veterinário',brl(581.40),'2026-09-07',''],['Serviço do carro',brl(235),'2026-09-01','Já pago antes do acompanhamento',true],['Multa',142000,'2026-09-01','Já paga antes do acompanhamento',true]
].map((x,i)=>({id:100+i,name:x[0],amount:x[1],due:x[2],note:x[3],paidAmount:x[4]?x[1]:0,history:x[4]?[{id:Date.now()+i,amount:x[1],date:'2026-09-01',note:'Pago antes do acompanhamento'}]:[]}));
const initial={goal:2841196,safetyMargin:100000,periodStart:'2026-09-01',periodEnd:'2026-10-05',selectedDate:localISO(),incomes:[{id:1,date:'2026-09-01',amount:40000,hours:4,note:'Ganho registrado em 1º de setembro'}],expenses:[{id:2,date:'2026-09-01',amount:53500,category:'Alimentação',note:'Registro inicial informado pelo usuário'}],study:[],quality:{},reminders:[],dailyActivities:{},bills:initialBills,lastBackup:null};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||initial;
data.goal??=2841196;data.safetyMargin??=100000;data.selectedDate??=localISO();data.incomes??=[];data.expenses??=[];data.study??=[];data.quality??={};data.reminders??=[];data.dailyActivities??={};data.bills??=[];data.bills.forEach(b=>{b.paidAmount??=(b.paid?b.amount:0);b.history??=[]});
const dailyPlan={0:[['🙏','Missa / compromisso religioso'],['🚗','Trabalho – meta de 5h'],['📚','Revisão leve']],1:[['🏫','Faculdade – manhã'],['📚','Estudo'],['🍳','Preparar comida, quando necessário'],['🏋️','Treino'],['🙏','Formação / compromisso']],2:[['🏫','Faculdade – manhã'],['🚗','Trabalho – meta de 5h'],['📚','Estudo'],['🏋️','Treino']],3:[['🎾','Tênis + deslocamento'],['🚗','Trabalho – meta de 8h30'],['📚','Estudo leve conforme recuperação']],4:[['🏫','Faculdade – manhã'],['🚗','Trabalho – meta de 4h30'],['📚','Estudo'],['🏋️','Treino']],5:[['🚗','Trabalho – meta de 8h30'],['🏋️','Treino, se recuperado'],['🙏','Cenáculo / compromisso à noite']],6:[['⚽','Futebol'],['🚗','Trabalho – meta de 9h30'],['📚','Revisão opcional']]};
const plannedGoalsByDay={0:70000,1:0,2:59204,3:106250,4:64830,5:125455,6:142500};
const plannedHoursByDay={0:5,1:0,2:5,3:8.5,4:4.5,5:8.5,6:9.5};
function selected(){return data.selectedDate}function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');scrollTo({top:0,behavior:'smooth'})}
function selectDate(d){if(d){data.selectedDate=d;save()}}function changeDay(n){const d=new Date(selected()+'T12:00');d.setDate(d.getDate()+n);data.selectedDate=d.toISOString().slice(0,10);save()}
function formatDate(d){return new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'))}
function plannedGoalFor(date){return plannedGoalsByDay[new Date(date+'T12:00').getDay()]||0}
function sum(arr,fn=x=>x.amount){return arr.reduce((a,x)=>a+Number(fn(x)||0),0)}
function billRemaining(b){return Math.max(0,Number(b.amount)-Number(b.paidAmount||0))}
function totalBillsRemaining(){return sum(data.bills,b=>billRemaining(b))}
const EXPECTED_INITIAL_PENDING=2679671;
function initialDataSelfCheck(){
  const pending=Math.round(sum(initialBills,b=>Math.max(0,b.amount-(b.paidAmount||0))));
  return pending===EXPECTED_INITIAL_PENDING;
}
function totalBillPaymentsTracked(){return sum(data.bills,b=>sum(b.history||[],p=>p.amount))}
function totalIncome(){return sum(data.incomes)}function totalExpenses(){return sum(data.expenses)}
function availableBalance(){return totalIncome()-totalExpenses()-totalBillPaymentsTracked()}
function dailyIncome(date){return sum(data.incomes.filter(x=>x.date===date))}function dailyExpense(date){return sum(data.expenses.filter(x=>x.date===date))}
function plannedAccumulated(){let total=0,d=new Date(data.periodStart+'T12:00'),end=new Date(selected()+'T12:00');if(end<d)return 0;for(;d<=end;d.setDate(d.getDate()+1))total+=plannedGoalFor(d.toISOString().slice(0,10));return total}
function dayPlan(date){const dow=new Date(date+'T12:00').getDay();const base=(dailyPlan[dow]||[]).map((x,i)=>({id:'base-'+dow+'-'+i,icon:x[0],name:x[1],done:false}));const custom=data.dailyActivities[date]||[];return base.map(x=>({...x,done:custom.find(a=>a.id===x.id)?.done||false})).concat(custom.filter(x=>!String(x.id).startsWith('base-')))}
function render(){const d=selected(),inc=dailyIncome(d),exp=dailyExpense(d),accInc=totalIncome(),remainingBills=totalBillsRemaining(),balance=availableBalance(),goalProgress=Math.max(0,Math.min(100,accInc/data.goal*100));
 todayText.textContent='Hoje: '+new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date(d+'T12:00'));
 selectedDateLabel.textContent=formatDate(d);routineDateLabel.textContent=formatDate(d);datePicker.value=d;routinePicker.value=d;quickDateText.textContent=formatDate(d);
 goalValue.textContent=money(data.goal);goalBar.style.width=goalProgress+'%';goalPct.textContent=goalProgress.toFixed(1).replace('.',',')+'% da meta por ganhos registrados';remaining.textContent='Faltam '+money(Math.max(0,data.goal-accInc));goalBasis.textContent='Meta editável. As contas diminuem separadamente quando você registra pagamentos.';
 dailyGoal.textContent=money(plannedGoalFor(d));todayIncome.textContent=signed(inc);todayIncome.className=inc?'positive':'';todayExpense.textContent=exp?signed(-exp):money(0);todayExpense.className=exp?'negative':'';incomeAccumulated.textContent=signed(accInc);incomeAccumulated.className=accInc?'positive':'';billsRemaining.textContent=money(remainingBills);netValue.textContent=signed(balance);netValue.className=balance>=0?'positive':'negative';
 const expected=plannedAccumulated(),diff=accInc-expected;statusText.innerHTML=`Até ${formatDate(d)}, seus ganhos registrados são <b>${money(accInc)}</b>. Pela meta diária acumulada, o planejado era <b>${money(expected)}</b>. Você está <b>${signed(diff)}</b> em relação ao ritmo planejado.`;
 planAudit.innerHTML=`<b>Visão financeira:</b><br>Contas ainda pendentes: <b>${money(remainingBills)}</b><br>Pagamentos de contas registrados: <b>${money(totalBillPaymentsTracked())}</b><br>Saldo disponível: <b class="${balance>=0?'positive':'negative'}">${signed(balance)}</b>`;
 renderList('incomeList',data.incomes,'income');renderList('expenseList',data.expenses,'expense');expenseSummary.innerHTML=`Total de gastos registrados: <b>${money(totalExpenses())}</b> • Pagamentos de contas: <b>${money(totalBillPaymentsTracked())}</b>`;
 const schedule=dayPlan(d); const actualHours=sum(data.incomes.filter(x=>x.date===d),x=>x.hours); const plannedHours=plannedHoursByDay[new Date(d+'T12:00').getDay()]||0; const workInfo=plannedHours>0?`<div class="workStatus">🚗 <b>Trabalho:</b> meta de ${plannedHours}h • realizado ${actualHours}h ${actualHours>=plannedHours?'🟢 Meta de horas atingida':'⚠️ Meta de horas não atingida'}<br>💰 Meta financeira: ${money(plannedGoalFor(d))} • ganho real: ${money(inc)} ${inc>=plannedGoalFor(d)?'🟢 Atingida':'⚠️ Ainda não atingida'}</div>`:''; dailySchedule.innerHTML=workInfo+schedule.map(a=>`<div class="activity"><button onclick="toggleActivity('${d}','${esc(a.id)}')">${a.done?'✅':'⬜'}</button><span>${a.icon} ${esc(a.name)}</span></div>`).join('')||'<span class="muted">Sem programação.</span>'; dailyChecklist.innerHTML=workInfo+schedule.map(a=>`<div class="activity"><button onclick="toggleActivity('${d}','${esc(a.id)}')">${a.done?'✅':'⬜'}</button><span>${a.icon} ${esc(a.name)}</span></div>`).join('');
 const q=data.quality[d]||{};qualitySummary.textContent='Treino: '+(q.treino||'não registrado')+' • Alimentação: '+(q.alimentacao||'não registrada');
 studyTotal.textContent='Estudo acumulado: '+sum(data.study,x=>x.hours).toFixed(1)+' h';selectedStudyTotal.textContent='Neste dia: '+sum(data.study.filter(x=>x.date===d),x=>x.hours).toFixed(1)+' h';routineList.innerHTML=schedule.map(a=>`<div class="activity"><button onclick="toggleActivity('${d}','${esc(a.id)}')">${a.done?'✅':'⬜'}</button><span>${a.icon} ${esc(a.name)}</span></div>`).join('');
 const upcoming=data.reminders.filter(r=>!r.done).sort((a,b)=>a.date.localeCompare(b.date));reminderList.innerHTML=upcoming.map(reminderHTML).join('')||'<div class="panel muted">Nenhum lembrete pendente.</div>';homeReminders.innerHTML=upcoming.slice(0,3).map(reminderHTML).join('')||'<span class="muted">Nenhum lembrete pendente.</span>';
 billList.innerHTML=[...data.bills].sort((a,b)=>a.due.localeCompare(b.due)).map(billHTML).join('')||'<div class="muted">Nenhuma conta cadastrada.</div>';
 financialSettings.innerHTML=`<div class="summaryLine">Meta do período: <b>${money(data.goal)}</b><br>Margem de segurança: <b>${money(data.safetyMargin)}</b><br>Período: ${formatDate(data.periodStart)} até ${formatDate(data.periodEnd)}</div>`;backupStatus.textContent=data.lastBackup?'Último backup exportado: '+formatDate(data.lastBackup):'Faça backups periódicos para guardar seus registros.';
}
function renderList(id,list,type){document.getElementById(id).innerHTML=[...list].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).map(x=>`<div class="entry"><div><strong>${type==='income'?'💰':'💸'} ${money(x.amount)}</strong><small>${formatDate(x.date)} ${x.hours?'• '+x.hours+'h':''}${x.category?'• '+esc(x.category):''}${x.note?'• '+esc(x.note):''}</small></div><button class="danger" onclick="deleteEntry('${type}',${x.id})">Excluir</button></div>`).join('')||'<div class="panel muted">Nenhum registro ainda.</div>'}
function openModal(h){modalContent.innerHTML=h;modal.classList.remove('hidden')}function closeModal(){modal.classList.add('hidden')}
function openIncome(){openModal(`<h2>Registrar ganho</h2><label>Valor em pesos<input id="mAmount" type="number"></label><label>Horas trabalhadas<input id="mHours" type="number" step=".5"></label><label>Data<input id="mDate" type="date" value="${selected()}"></label><label>Observação<input id="mNote"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveIncome()">Salvar</button></div>`)}function saveIncome(){if(!+mAmount.value)return alert('Informe um valor');data.incomes.push({id:Date.now(),amount:+mAmount.value,hours:+mHours.value||0,date:mDate.value,note:mNote.value});save();closeModal()}
function openExpense(){openModal(`<h2>Registrar gasto</h2><label>Categoria<select id="mCategory"><option>Gasolina</option><option>Alimentação</option><option>Casa</option><option>Carro</option><option>Faculdade</option><option>Saúde</option><option>Outro</option></select></label><label>Valor<input id="mAmount" type="number"></label><label>Data<input id="mDate" type="date" value="${selected()}"></label><label>Observação<input id="mNote"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveExpense()">Salvar</button></div>`)}function saveExpense(){if(!+mAmount.value)return alert('Informe um valor');data.expenses.push({id:Date.now(),amount:+mAmount.value,date:mDate.value,category:mCategory.value,note:mNote.value});save();closeModal()}
function openStudy(){openModal(`<h2>Registrar estudo</h2><label>Horas<input id="mHours" type="number" step=".5"></label><label>Data<input id="mDate" type="date" value="${selected()}"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveStudy()">Salvar</button></div>`)}function saveStudy(){if(!+mHours.value)return alert('Informe as horas');data.study.push({id:Date.now(),hours:+mHours.value,date:mDate.value});save();closeModal()}function addStudy(h){data.study.push({id:Date.now(),hours:h,date:selected()});save()}
function setQuality(t,v){data.quality[selected()]??={};data.quality[selected()][t]=v;save()}
function toggleActivity(date,id){data.dailyActivities[date]??=[];let a=data.dailyActivities[date].find(x=>String(x.id)===String(id));if(!a){const base=dayPlan(date).find(x=>String(x.id)===String(id));if(!base)return;a={...base};data.dailyActivities[date].push(a)}a.done=!a.done;save()}function addCustomActivity(){const n=prompt('Qual atividade deseja adicionar?');if(n){data.dailyActivities[selected()]??=[];data.dailyActivities[selected()].push({id:'custom-'+Date.now(),icon:'📌',name:n,done:false});save()}}
function addReminder(){openModal(`<h2>Novo lembrete</h2><label>Título<input id="mTitle"></label><label>Data<input id="mDate" type="date" value="${selected()}"></label><label>Avisar quantos dias antes?<input id="mBefore" type="number" value="5"></label><label>Importância<select id="mImportance"><option>Normal</option><option>Importante</option><option>Urgente</option></select></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveReminder()">Salvar</button></div>`)}function saveReminder(){if(!mTitle.value||!mDate.value)return alert('Preencha título e data');data.reminders.push({id:Date.now(),title:mTitle.value,date:mDate.value,before:+mBefore.value||0,importance:mImportance.value,done:false});save();closeModal()}function reminderHTML(r){return `<div class="reminderRow"><div><strong>${esc(r.title)}</strong><small>${formatDate(r.date)} • ${esc(r.importance)}</small></div><button onclick="toggleReminder(${r.id})">Concluir</button></div>`}function toggleReminder(id){const x=data.reminders.find(x=>x.id===id);x.done=!x.done;save()}
function deleteEntry(t,id){if(confirm('Excluir este registro?')){const k=t==='income'?'incomes':'expenses';data[k]=data[k].filter(x=>x.id!==id);save()}}
function billHTML(b){const remaining=billRemaining(b),paid=remaining===0;return `<div class="billRow ${paid?'done':''}"><div><strong>${esc(b.name)}</strong><small>Total: ${money(b.amount)} • Pago: ${money(b.paidAmount||0)} • Restante: ${money(remaining)}<br>Vencimento: ${formatDate(b.due)}${b.note?' • '+esc(b.note):''}</small></div><div><span class="${paid?'paidBadge':'unpaidBadge'}">${paid?'✓ Paga':'Pendente'}</span><br>${!paid?`<button onclick="payBill(${b.id})">Registrar pagamento</button>`:''}<button onclick="editBill(${b.id})">Editar</button><button class="danger" onclick="deleteBill(${b.id})">Excluir</button></div></div>`}
function payBill(id){const b=data.bills.find(x=>x.id===id),rest=billRemaining(b);openModal(`<h2>Pagamento: ${esc(b.name)}</h2><p>Restante: <b>${money(rest)}</b></p><label>Valor pago<input id="mPay" type="number" value="${rest}"></label><label>Data<input id="mDate" type="date" value="${selected()}"></label><label>Observação<input id="mNote"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveBillPayment(${id})">Registrar pagamento</button></div>`)}function saveBillPayment(id){const b=data.bills.find(x=>x.id===id),v=+mPay.value,rest=billRemaining(b);if(!v||v>rest)return alert('Informe um valor entre 1 e '+fmt(rest));b.paidAmount+=v;b.history.push({id:Date.now(),amount:v,date:mDate.value,note:mNote.value});save();closeModal()}
function addBill(){openBillModal()}function openBillModal(b){openModal(`<h2>${b?'Editar conta':'Nova conta'}</h2><label>Nome<input id="mName" value="${esc(b?.name||'')}"></label><label>Valor total em pesos<input id="mAmount" type="number" value="${b?.amount||''}"></label><label>Vencimento<input id="mDate" type="date" value="${b?.due||selected()}"></label><label>Observação<input id="mBillNote" value="${esc(b?.note||'')}"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="${b?'saveBillEdit('+b.id+')':'saveBill()'}">Salvar</button></div>`)}function saveBill(){if(!mName.value||!+mAmount.value||!mDate.value)return alert('Preencha os campos');data.bills.push({id:Date.now(),name:mName.value,amount:+mAmount.value,due:mDate.value,note:mBillNote.value,paidAmount:0,history:[]});save();closeModal()}function editBill(id){openBillModal(data.bills.find(x=>x.id===id))}function saveBillEdit(id){const b=data.bills.find(x=>x.id===id);if(+mAmount.value<(b.paidAmount||0))return alert('O total não pode ser menor que o já pago.');Object.assign(b,{name:mName.value,amount:+mAmount.value,due:mDate.value,note:mBillNote.value});save();closeModal()}function deleteBill(id){if(confirm('Excluir esta conta?')){data.bills=data.bills.filter(x=>x.id!==id);save()}}
function openFinancialSettings(){openModal(`<h2>Editar metas financeiras</h2><label>Meta total do período<input id="mGoal" type="number" value="${data.goal}"></label><label>Margem de segurança (informativa)<input id="mMargin" type="number" value="${data.safetyMargin}"></label><label>Início<input id="mStart" type="date" value="${data.periodStart}"></label><label>Fim<input id="mEnd" type="date" value="${data.periodEnd}"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveFinancialSettings()">Salvar</button></div>`)}function saveFinancialSettings(){data.goal=+mGoal.value;data.safetyMargin=+mMargin.value;data.periodStart=mStart.value;data.periodEnd=mEnd.value;save();closeModal()}
function exportBackup(){const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='backup-minha-meta-'+localISO()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);data.lastBackup=localISO();save()}function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||typeof x!=='object')throw 0;data=x;data.selectedDate??=localISO();data.bills??=[];data.bills.forEach(b=>{b.paidAmount??=0;b.history??=[]});save();alert('Backup importado com sucesso!')}catch{alert('Arquivo de backup inválido.')}};r.readAsText(f)}
console.assert(initialDataSelfCheck(),'Erro na base inicial das contas');
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});render();
