const KEY='minha_meta_v11', OLD_KEYS=['minha_meta_v9','minha_meta_v8','minha_meta_v7','minha_meta_v6','minha_meta_v5','minha_meta_v4'];
const fmt=n=>new Intl.NumberFormat('es-AR',{maximumFractionDigits:0}).format(Number(n||0)); const money=n=>'$ '+fmt(n);
const localISO=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const initial={obligationsGoal:2741196,safetyMargin:100000,goal:2841196,lastBackup:null,periodStart:'2026-09-01',periodEnd:'2026-10-05',selectedDate:localISO(),incomes:[{id:1,date:'2026-09-01',amount:40000,hours:4,note:'Ganho registrado em 1º de setembro'}],expenses:[],study:[],quality:{},reminders:[],dailyActivities:{},bills:[]};
let data=JSON.parse(localStorage.getItem(KEY)||'null'); if(!data){for(const k of OLD_KEYS){const x=localStorage.getItem(k);if(x){data=JSON.parse(x);break}}} if(!data)data=initial;
data.dailyActivities??={}; data.selectedDate??=localISO(); data.obligationsGoal??=2741196;data.safetyMargin??=100000;data.bills??=[]; data.quality??={};data.study??=[];data.expenses??=[];data.incomes??=[];data.reminders??=[]; data.lastBackup??=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
function recalcGoal(){data.goal=+data.obligationsGoal+ +data.safetyMargin} recalcGoal();
const dailyPlan={0:[['🙏','Missa – preferência por volta de 12h'],['🚗','Trabalho – cerca de 5h'],['📚','Revisão leve para segunda'],['🧹','Limpeza da casa – 1h a 1h30 (se planejada)']],1:[['🏫','Faculdade: Fisiologia – 8h às 12h'],['📚','Estudo de Bioquímica em casa – cerca de 3h'],['🍳','Preparar comida da semana – quando necessário'],['🏋️','Treino com barra – 30 min'],['🙏','Formação Aliança da Misericórdia – 19h às 22h']],2:[['🏫','Faculdade: Bioquímica – 8h às 12h'],['🚗','Trabalho – meta de 4h30'],['📚','Estudo – aproximadamente 19h às 22h'],['🏋️','Treino com barra – 30 min']],3:[['🎾','Tênis + deslocamento – aproximadamente 13h30 às 15h30'],['🚗','Trabalho – meta de 8h30'],['📚','Estudo leve/revisão conforme recuperação']],4:[['🏫','Faculdade: Integração de Fisiologia – 8h às 12h'],['🚗','Trabalho – meta de 4h30'],['📚','Estudo – aproximadamente 19h às 22h'],['🏋️','Treino com barra – 30 min']],5:[['🚗','Trabalho – meta de 8h30'],['🏋️','Treino com barra – 30 min, se recuperado'],['🍳','Preparar comida da semana – alternativa'],['🙏','Senac – 19h30 às 22h30']],6:[['⚽','Futebol – aproximadamente 10h30 às 12h30'],['🚗','Trabalho – meta de 9h30'],['📚','Revisão opcional']],};

// Metas planejadas por dia da semana, conforme o seu plano de trabalho.
// 0=domingo, 1=segunda, 2=terça, 3=quarta, 4=quinta, 5=sexta, 6=sábado.
// Metas ajustadas para cobrir os $128.696 que faltavam no planejamento anterior.
// O acréscimo foi distribuído somente entre terça, quinta e sexta, como solicitado.
const plannedGoalsByDay={0:70000,1:0,2:59204,3:106250,4:64830,5:125455,6:142500};
// Ajuste técnico de $1 em uma sexta-feira para que a soma de todo o período seja exatamente $2.841.196.
const plannedGoalOverrides={'2026-10-02':125456};
const plannedHoursByDay={0:5,1:0,2:4.5,3:8.5,4:4.5,5:8.5,6:9.5};
function plannedGoalFor(date){return plannedGoalOverrides[date]??(plannedGoalsByDay[new Date(date+'T12:00').getDay()]??0)}
function calculatePlannedTotal(start,end){let total=0,d=new Date(start+'T12:00'),last=new Date(end+'T12:00');for(;d<=last;d.setDate(d.getDate()+1)){total+=plannedGoalFor(d.toISOString().slice(0,10))}return total}

function dayPlan(date){const dow=new Date(date+'T12:00').getDay();const base=(dailyPlan[dow]||[]).map((x,i)=>({id:'base-'+dow+'-'+i,icon:x[0],name:x[1],done:false}));const custom=(data.dailyActivities[date]||[]);return [...base,...custom];}
function selected(){return data.selectedDate} function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function selectDate(d){if(!d)return;data.selectedDate=d;save()} function changeDay(n){const d=new Date(selected()+'T12:00');d.setDate(d.getDate()+n);data.selectedDate=d.toISOString().slice(0,10);save()}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0)} function sum(a,f){return a.reduce((s,x)=>s+Number(f(x)||0),0)}
function render(){const sd=selected(), now=localISO(); const dateObj=new Date(sd+'T12:00');const dateLabel=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(dateObj);
 document.getElementById('todayText').textContent='Data selecionada: '+dateLabel;['selectedDateLabel','routineDateLabel'].forEach(id=>document.getElementById(id).textContent=dateLabel);['datePicker','routinePicker'].forEach(id=>document.getElementById(id).value=sd);document.getElementById('quickDateText').textContent=formatDate(sd);
 const income=sum(data.incomes,x=>x.amount),expense=sum(data.expenses,x=>x.amount),net=income-expense;
 const inc=sum(data.incomes.filter(x=>x.date===sd),x=>x.amount),exp=sum(data.expenses.filter(x=>x.date===sd),x=>x.amount);
 // Saldo acumulado até a data selecionada: considera somente registros daquele dia e dos dias anteriores.
 const cumulativeIncome=sum(data.incomes.filter(x=>x.date<=sd),x=>x.amount);
 const cumulativeExpense=sum(data.expenses.filter(x=>x.date<=sd),x=>x.amount);
 const cumulativeNet=cumulativeIncome-cumulativeExpense;
 const remaining=Math.max(0,data.goal-income); // meta de trabalho acompanha ganhos, não saldo líquido
 const remainingBySelected=Math.max(0,data.goal-cumulativeIncome);const until=Math.max(1,Math.ceil((new Date(data.periodEnd+'T23:59:59')-new Date(now+'T00:00:00'))/86400000));const calculatedAverage=Math.ceil(remaining/until);const plannedGoal=plannedGoalFor(sd);const plannedHours=plannedHoursByDay[dateObj.getDay()]??0;const pct=Math.min(100,Math.max(0,income/data.goal*100));
 goalValue.textContent=money(data.goal);goalBar.style.width=pct+'%';goalPct.textContent=pct.toFixed(1).replace('.',',')+'% concluído';remaining.textContent='Faltam '+money(remaining); goalBasis.textContent='Progresso calculado pelos ganhos efetivamente registrados.';dailyGoal.textContent=plannedGoal?money(plannedGoal):'Sem meta de trabalho';todayIncome.textContent=money(inc);todayExpense.textContent=money(exp);netValue.textContent=money(cumulativeNet);incomeAccumulated.textContent=money(cumulativeIncome);
 if(plannedGoal===0){statusText.textContent='🔵 Nesta data não há meta planejada de trabalho. O foco principal é a sua rotina programada.';averageText.textContent='Meta financeira geral: '+money(data.goal)+' • Média necessária atual: '+money(calculatedAverage)+' por dia restante.'}else{statusText.textContent=inc>=plannedGoal?'🟢 Nesta data, você atingiu a meta planejada de '+money(plannedGoal)+'.':'🟡 Nesta data, faltaram '+money(Math.max(0,plannedGoal-inc))+' para atingir a meta planejada de '+money(plannedGoal)+'.';averageText.textContent='Meta planejada: '+money(plannedGoal)+' para aproximadamente '+plannedHours.toString().replace('.',',')+'h de trabalho • Média necessária atual: '+money(calculatedAverage)+' por dia restante.';}
 const q=data.quality[sd]||{};qualitySummary.textContent='Em '+formatDate(sd)+': treino – '+(q.treino||'não registrado')+' | alimentação – '+(q.alimentacao||'não registrada');
 dailySchedule.innerHTML=dayPlan(sd).map(a=>`<div class="scheduleRow ${a.done?'done':''}"><span>${esc(a.icon)} ${esc(a.name)}</span></div>`).join('');dailyChecklist.innerHTML=dayPlan(sd).map(a=>`<div class="routineRow ${a.done?'done':''}"><span>${esc(a.icon)} ${esc(a.name)}</span><input style="width:auto" type="checkbox" ${a.done?'checked':''} onchange="toggleActivity('${sd}','${a.id}')"></div>`).join('');
 renderList('incomeList',data.incomes,'income');renderList('expenseList',data.expenses,'expense');const gas=sum(data.expenses.filter(x=>x.category==='Gasolina'),x=>x.amount),food=sum(data.expenses.filter(x=>x.category==='Alimentação'),x=>x.amount);expenseSummary.textContent='Total gasto: '+money(expense)+' • Gasolina: '+money(gas)+' • Alimentação: '+money(food);
 studyTotal.textContent='Total de estudos registrado: '+sum(data.study,x=>x.hours).toFixed(1).replace('.',',')+' horas';selectedStudyTotal.textContent='Neste dia: '+sum(data.study.filter(x=>x.date===sd),x=>x.hours).toFixed(1).replace('.',',')+' horas';routineList.innerHTML=dayPlan(sd).map(a=>`<div class="routineRow ${a.done?'done':''}"><span>${esc(a.icon)} ${esc(a.name)}</span><input style="width:auto" type="checkbox" ${a.done?'checked':''} onchange="toggleActivity('${sd}','${a.id}')"></div>`).join('');
 const upcoming=data.reminders.filter(r=>!r.done).sort((a,b)=>a.date.localeCompare(b.date));reminderList.innerHTML=upcoming.length?upcoming.map(reminderHTML).join(''):'<div class="panel muted">Nenhum lembrete pendente.</div>';homeReminders.innerHTML=upcoming.slice(0,3).length?upcoming.slice(0,3).map(reminderHTML).join(''):'<span class="muted">Nenhum lembrete pendente.</span>';
 billList.innerHTML=data.bills.sort((a,b)=>a.due.localeCompare(b.due)).map(b=>{const bs=billStatus(b);return `<div class="billRow ${b.paid?'done':''}"><div><strong>${esc(b.name)}</strong><small>${money(b.amount)} • vence ${formatDate(b.due)}${b.note?' • '+esc(b.note):''}</small></div><div><span class="${bs.cls}">${bs.text}</span><br><button onclick="toggleBill(${b.id})">${b.paid?'Desmarcar':'Marcar como paga'}</button><button onclick="editBill(${b.id})">Editar</button><button class="danger" onclick="deleteBill(${b.id})">Excluir</button></div></div>`}).join('')||'<div class="muted">Nenhuma conta cadastrada.</div>';
 const planTotal=calculatePlannedTotal(data.periodStart,data.periodEnd); const planDiff=planTotal-data.goal;
 planAudit.innerHTML='<b>Auditoria do planejamento:</b><br>Metas diárias previstas no período: <b>'+money(planTotal)+'</b><br>Diferença para a meta financeira: <b>'+money(planDiff)+'</b> '+(planDiff>=0?'🟢 margem no planejamento':'🔴 falta planejamento');
 backupStatus.textContent=data.lastBackup?'Último backup exportado: '+formatDate(data.lastBackup):'Nenhum backup exportado nesta versão ainda.';
 financialSettings.innerHTML=`<div class="summaryLine">Obrigações: <b>${money(data.obligationsGoal)}</b><br>Margem: <b>${money(data.safetyMargin)}</b><br>Meta final: <b>${money(data.goal)}</b><br>Período: ${formatDate(data.periodStart)} até ${formatDate(data.periodEnd)}</div>`;
}
function renderList(id,list,type){document.getElementById(id).innerHTML=[...list].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="entry"><div><strong>${type==='income'?'💰':'💸'} ${money(x.amount)}</strong><small>${formatDate(x.date)} ${x.hours?'• '+x.hours+'h':''}${x.category?' • '+esc(x.category):''}${x.note?' • '+esc(x.note):''}</small></div><button class="danger" onclick="deleteEntry('${type}',${x.id})">Excluir</button></div>`).join('')||'<div class="panel muted">Nenhum registro ainda.</div>'}
function formatDate(d){return new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'))}
function openModal(h){modalContent.innerHTML=h;modal.classList.remove('hidden')}function closeModal(){modal.classList.add('hidden')}
function openIncome(){openModal(`<h2>Registrar ganho</h2><label>Valor em pesos<input id="mAmount" type="number"></label><label>Horas trabalhadas<input id="mHours" type="number" step=".5"></label><label>Data<input id="mDate" type="date" value="${selected()}"></label><label>Observação<input id="mNote"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveIncome()">Salvar</button></div>`)}function saveIncome(){if(!+mAmount.value)return alert('Informe um valor');data.incomes.push({id:Date.now(),amount:+mAmount.value,hours:+mHours.value||0,date:mDate.value,note:mNote.value});save();closeModal()}
function openExpense(){openModal(`<h2>Registrar gasto</h2><label>Categoria<select id="mCategory"><option>Gasolina</option><option>Alimentação</option><option>Casa</option><option>Carro</option><option>Faculdade</option><option>Saúde</option><option>Outro</option></select></label><label>Valor<input id="mAmount" type="number"></label><label>Data<input id="mDate" type="date" value="${selected()}"></label><label>Observação<input id="mNote"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveExpense()">Salvar</button></div>`)}function saveExpense(){if(!+mAmount.value)return alert('Informe um valor');data.expenses.push({id:Date.now(),amount:+mAmount.value,date:mDate.value,category:mCategory.value,note:mNote.value});save();closeModal()}
function openStudy(){openModal(`<h2>Registrar estudo</h2><label>Horas<input id="mHours" type="number" step=".5"></label><label>Data<input id="mDate" type="date" value="${selected()}"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveStudy()">Salvar</button></div>`)}function saveStudy(){if(!+mHours.value)return alert('Informe as horas');data.study.push({id:Date.now(),hours:+mHours.value,date:mDate.value});save();closeModal()}function addStudy(h){data.study.push({id:Date.now(),hours:h,date:selected()});save()}
function setQuality(t,v){data.quality[selected()]??={};data.quality[selected()][t]=v;save()}
function toggleActivity(date,id){const dow=new Date(date+'T12:00').getDay();if(id.startsWith('base-')){data.dailyActivities[date]??=[];let a=data.dailyActivities[date].find(x=>x.id===id);if(!a){const i=+id.split('-').pop(),b=dailyPlan[dow][i];a={id,icon:b[0],name:b[1],done:false};data.dailyActivities[date].push(a)}a.done=!a.done}else{const a=(data.dailyActivities[date]||[]).find(x=>String(x.id)===String(id));if(a)a.done=!a.done}save()}
function addCustomActivity(){let n=prompt('Qual atividade deseja adicionar para '+formatDate(selected())+'?');if(n){data.dailyActivities[selected()]??=[];data.dailyActivities[selected()].push({id:'custom-'+Date.now(),icon:'📌',name:n,done:false});save()}}
function addReminder(){openModal(`<h2>Novo lembrete</h2><label>Título<input id="mTitle"></label><label>Data<input id="mDate" type="date" value="${selected()}"></label><label>Avisar quantos dias antes?<input id="mBefore" type="number" value="5"></label><label>Importância<select id="mImportance"><option>Normal</option><option>Importante</option><option>Urgente</option></select></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveReminder()">Salvar</button></div>`)}function saveReminder(){if(!mTitle.value||!mDate.value)return alert('Preencha título e data');data.reminders.push({id:Date.now(),title:mTitle.value,date:mDate.value,before:+mBefore.value||0,importance:mImportance.value,done:false});save();closeModal()}
function reminderHTML(r){const diff=Math.ceil((new Date(r.date+'T12:00')-new Date(localISO()+'T12:00'))/86400000),warn=diff<=r.before&&diff>=0?' 🔔':'';return `<div class="reminderRow"><div><strong>${esc(r.title)}${warn}</strong><small>${formatDate(r.date)} • ${r.importance} • avisar ${r.before} dias antes</small></div><button onclick="toggleReminder(${r.id})">${r.done?'Reabrir':'Concluir'}</button></div>`}function toggleReminder(id){const x=data.reminders.find(x=>x.id===id);x.done=!x.done;save()}
function deleteEntry(t,id){if(confirm('Excluir este registro?')){const k=t==='income'?'incomes':'expenses';data[k]=data[k].filter(x=>x.id!==id);save()}}
function billStatus(b){if(b.paid)return {text:'✓ Paga',cls:'paidBadge'};const today=localISO();const diff=Math.ceil((new Date(b.due+'T12:00')-new Date(today+'T12:00'))/86400000);if(diff<0)return {text:'🔴 Vencida',cls:'unpaidBadge'};if(diff<=5)return {text:'🟠 Vence em breve',cls:'unpaidBadge'};return {text:'⚪ Futura',cls:'unpaidBadge'}}
function toggleBill(id){const b=data.bills.find(x=>x.id===id);b.paid=!b.paid;save()}function addBill(){openBillModal()}function openBillModal(b){openModal(`<h2>${b?'Editar conta':'Nova conta'}</h2><label>Nome<input id="mName" value="${esc(b?.name||'')}"></label><label>Valor em pesos<input id="mAmount" type="number" value="${b?.amount||''}"></label><label>Vencimento<input id="mDate" type="date" value="${b?.due||selected()}"></label><label>Observação<input id="mBillNote" value="${esc(b?.note||'')}"></label><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="${b?'saveBillEdit('+b.id+')':'saveBill()'}">Salvar</button></div>`)}function saveBill(){if(!mName.value||!+mAmount.value||!mDate.value)return alert('Preencha todos os campos');data.bills.push({id:Date.now(),name:mName.value,amount:+mAmount.value,due:mDate.value,note:mBillNote.value,paid:false});save();closeModal()}function editBill(id){openBillModal(data.bills.find(x=>x.id===id))}function saveBillEdit(id){const b=data.bills.find(x=>x.id===id);Object.assign(b,{name:mName.value,amount:+mAmount.value,due:mDate.value,note:mBillNote.value});save();closeModal()}function deleteBill(id){if(confirm('Excluir esta conta?')){data.bills=data.bills.filter(x=>x.id!==id);save()}}
function exportBackup(){const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='backup-minha-meta-v11-'+localISO()+'.json';a.click();URL.revokeObjectURL(a.href);data.lastBackup=localISO();localStorage.setItem(KEY,JSON.stringify(data));render()}function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);data.selectedDate??=localISO();data.dailyActivities??={};recalcGoal();save();alert('Backup importado!')}catch{alert('Arquivo inválido')}};r.readAsText(f)}
function openFinancialSettings(){openModal(`<h2>Editar metas financeiras</h2><label>Total das obrigações<input id="mObligations" type="number" value="${data.obligationsGoal}"></label><label>Margem de segurança<input id="mMargin" type="number" value="${data.safetyMargin}"></label><label>Início<input id="mStart" type="date" value="${data.periodStart}"></label><label>Fim<input id="mEnd" type="date" value="${data.periodEnd}"></label><p class="muted">Meta final = obrigações + margem.</p><div class="formActions"><button onclick="closeModal()">Cancelar</button><button class="success" onclick="saveFinancialSettings()">Salvar</button></div>`)}function saveFinancialSettings(){data.obligationsGoal=+mObligations.value;data.safetyMargin=+mMargin.value;data.periodStart=mStart.value;data.periodEnd=mEnd.value;recalcGoal();save();closeModal()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});render();
